### ISSUE TITLE
Trouble with definition of cvxP lambda

### ISSUE THREAD

**Issue by boomerTN** [empet/geom_modeling#1]
Hello,

I am an old-timey programmer (started with PDP-8 in 1967) who today works for Siemens Healthcare (recently renamed to Siemens Healthineers) in the Detector R&D Group in Rockford, TN. I am a principal scientist by title but spend my time supporting users of an innovative produce, the BrainPET - a PET scanner (Positron Emission Tomography) that operates in the bore of an MRI. 

I have been writing code using assembly language, C, Fortran, Tcl/Tk, IDL, and probably other languages that I have forgotten over the years. I even wrote my own operating system/interpretive programming language, ORACL, that was used in the 70's and early 80's for programming data acquisition and analysis problems in the fields of gamma and x-ray spectroscopy. 

So much for a short history...I am trying to extend my capabilities, especially in regard to programming in Python. I've dabbled in it off and on for a couple of years, never very seriously, but now feel that I should begin using it more, especially since most of my current projects involve data analysis using IDL and IDL, being a very closed and expensive language, is becoming harder and harder to deal with. I am aware of the open source alternative (whose name eludes me at the moment - I am 68 years old and my memory is not quite as sharp as it used to be) but wasn't overly impressed with it.

So, anyway, I discovered Jupyter Notebook and feel it is something worth my time to learn to use as a tool. They say "You can't teach an old dog new tricks" but this old dog is trying my best.

In my searching for examples of interactive plotting using python, I came across one of your projects, and was very intrigued by your mixture of math and programming. So I am trying to work through it (  FP-Bezier-Bspline.ipynb ).

The specific problem occurs in the cell that defines the cvxCtlP(ctrl, t) function:

cvx=lambda x, y, t: (1-t) \* x + t \* y # affine/convex combination of two numbers x, y

cvxP=lambda (P, Q, t): (cvx(P[0], Q[0], t), cvx(P[1], Q[1], t))# affine/cvx comb of two points P,Q

When I enter this cell into my running Jupyter Notebook, I get an error...
￼

cvx=lambda x, y, t: (1-t) \* x + t \* y # affine/convex combination of two numbers x, y
​
cvxP = lambda (P, Q, t)  : (cvx(P[0], Q[0], t), cvx(P[1], Q[1], t)) # affine/cvx comb of two points P,Q
​

def cvxCtrlP(ctrl, t):# affine/cvx combination of each two consecutive points in a list ctrl 
                      # with the same coefficient t  
    return map(cvxP, zip(ctrl[:-1], ctrl[1:], [t]*(len(ctrl)-1))) 
  File "<ipython-input-23-0d233d19d8e0>", line 3
    cvxP = lambda (P, Q, t)  : (cvx(P[0], Q[0], t), cvx(P[1], Q[1], t)) # affine/cvx comb of two points P,Q
                  ^
SyntaxError: invalid syntax

The error actually points to the left parentheses. 

If I remove the parentheses from the lambda definition, the error message goes away but the program doesn't work (after putting in the rest of the cells). The graph is displayed and I am able to input points using the left mouse button, but pressing the right mouse button has not effect. I think this is because my redefinition of cvxP without the parentheses is incorrect.

When I take the same code and put it in a file and execute it with standalone python it works perfectly. If I remove the parentheses it crashes complaining that the lambda cvxP requires 3 arguments but only one is passed, the zip(...)

I just discovered that the code works with python 2.7.3 but fails with python 3.2.3 - so at least my stumblings have identified the issue. I'll have to research how to do this in python 3.

I'm just crawling along in my learning of python and decided that I should concentrate on python 3 since that is definitely the future, but it seems you are using a technique that is broken in python 3 or that maybe has another way of doing the same thing.

Perhaps you can help me in my learning process as it seems you are a prolific contributor (I am just beginning to explore your github submissions) and I seem to learn best when I study code of successful people. So if you have an answer to how to fix the lambda definition so that it works in python 3 or have any other comments about this lengthy post, I'd be humbled at your response.

Many thanks for making your work public. Unfortunately because I have been and continue to be employed by very secretive companies, I have not been able to share much of my work with more than a few collaborators over the years. But now that I'm nearing retirement, I'd like to try to publish some of what I have learned in my long journey.

I appreciate your feedback.

With best regards,

Larry Byars
Principal Scientist
Detector R&D
Siemens Healthineers   :-)

**Comment by empet** [comment]
@boomerTN  All my jupyter notebooks contain code in Python 2.7x
That is why you get errors when you  run the notebook with Python 3.

Here [http://nbviewer.jupyter.org/gist/empet/a5f18fded22fcc0546b96c2dbee49b7e](http://nbviewer.jupyter.org/gist/empet/a5f18fded22fcc0546b96c2dbee49b7e)
I defined Python 3 versions for `cvxP` and `cvxCtrlP` , and tested the code with Python 3.5.

**Comment by boomerTN** [comment]
On 05/19/2016 01:01 PM, empet wrote:

> Closed #1 https://github.com/empet/geom_modeling/issues/1.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> https://github.com/empet/geom_modeling/issues/1#event-666094039
> 
> Thanks for the quick solution.

Larry Byars
